.TH COPYFS-DAEMON "1" "October 2006" "copyfs-daemon" "User Commands"
.SH NAME
copyfs-daemon
.SH SYNOPSIS
.B copyfs-daemon
[\fIOPTIONS\fR]...
.SH DESCRIPTION
This is the copyfs-daemon. You should not run this program directly, instead, use copyfs-mount.
.SH AUTHORS
CopyFS was created by Thomas Joubert and Nicolas Vigier <boklm@mars-attacks.org>
.SH "MORE INFOS"

http://n0x.org/copyfs/

.SH SEE ALSO
copyfs(1), copyfs-fversion(1), copyfs-mount(1)
